device: Sailow CTD
atlas-sensors:
  dissolved-oxygen:
    name: "Dissolved Oxygen"
    address: 0x61
  conductivity:
    name: "Conductivity Probe"
    address: 0x64
  temperature-do:
    name: "Temperature from Dissolved Oxygen Sensor"
    address: 0x66
bluerobotics-sensors:
  depth:
    name: "Depth Sensor"
    address: 0x76
